"""
1000 stress test cases — casual, productivity, and code-related tasks.
Organized by tag for selective filtering.

Tags:
  greeting, identity, knowledge, fun, weather, math, productivity, writing,
  code-python, code-js, code-sql, code-web, code-api, code-git, code-devops,
  data, ml, system, multilang, context
"""

CASES = [
    # ═══════════════════════════════════════════════════════════════════════
    # GREETING — casual greetings and small talk (1-50)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 1, "tag": "greeting", "msgs": ["hello"]},
    {"id": 2, "tag": "greeting", "msgs": ["hi"]},
    {"id": 3, "tag": "greeting", "msgs": ["hey"]},
    {"id": 4, "tag": "greeting", "msgs": ["good morning"]},
    {"id": 5, "tag": "greeting", "msgs": ["good afternoon"]},
    {"id": 6, "tag": "greeting", "msgs": ["good evening"]},
    {"id": 7, "tag": "greeting", "msgs": ["howdy"]},
    {"id": 8, "tag": "greeting", "msgs": ["yo"]},
    {"id": 9, "tag": "greeting", "msgs": ["sup"]},
    {"id": 10, "tag": "greeting", "msgs": ["what's up"]},
    {"id": 11, "tag": "greeting", "msgs": ["how are you"]},
    {"id": 12, "tag": "greeting", "msgs": ["how's it going"]},
    {"id": 13, "tag": "greeting", "msgs": ["how do you do"]},
    {"id": 14, "tag": "greeting", "msgs": ["thanks"]},
    {"id": 15, "tag": "greeting", "msgs": ["thank you"]},
    {"id": 16, "tag": "greeting", "msgs": ["thanks a lot"]},
    {"id": 17, "tag": "greeting", "msgs": ["appreciate it"]},
    {"id": 18, "tag": "greeting", "msgs": ["ok"]},
    {"id": 19, "tag": "greeting", "msgs": ["got it"]},
    {"id": 20, "tag": "greeting", "msgs": ["sure"]},
    {"id": 21, "tag": "greeting", "msgs": ["cool"]},
    {"id": 22, "tag": "greeting", "msgs": ["nice"]},
    {"id": 23, "tag": "greeting", "msgs": ["great"]},
    {"id": 24, "tag": "greeting", "msgs": ["awesome"]},
    {"id": 25, "tag": "greeting", "msgs": ["good night"]},
    {"id": 26, "tag": "greeting", "msgs": ["bye"]},
    {"id": 27, "tag": "greeting", "msgs": ["see you later"]},
    {"id": 28, "tag": "greeting", "msgs": ["have a nice day"]},
    {"id": 29, "tag": "greeting", "msgs": ["cheers"]},
    {"id": 30, "tag": "greeting", "msgs": ["yo what's good"]},
    {"id": 31, "tag": "greeting", "msgs": ["hey there, how's your day"]},
    {"id": 32, "tag": "greeting", "msgs": ["hi, long time no see"]},
    {"id": 33, "tag": "greeting", "msgs": ["morning!"]},
    {"id": 34, "tag": "greeting", "msgs": ["evening!"]},
    {"id": 35, "tag": "greeting", "msgs": ["hey hey"]},
    {"id": 36, "tag": "greeting", "msgs": ["hola"]},
    {"id": 37, "tag": "greeting", "msgs": ["bonjour"]},
    {"id": 38, "tag": "greeting", "msgs": ["hi there"]},
    {"id": 39, "tag": "greeting", "msgs": ["greetings"]},
    {"id": 40, "tag": "greeting", "msgs": ["what's happening"]},
    {"id": 41, "tag": "greeting", "msgs": ["long time"]},
    {"id": 42, "tag": "greeting", "msgs": ["hey buddy"]},
    {"id": 43, "tag": "greeting", "msgs": ["hi friend"]},
    {"id": 44, "tag": "greeting", "msgs": ["good to see you"]},
    {"id": 45, "tag": "greeting", "msgs": ["yo, I'm back"]},
    {"id": 46, "tag": "greeting", "msgs": ["hi, missed you"]},
    {"id": 47, "tag": "greeting", "msgs": ["hello hello"]},
    {"id": 48, "tag": "greeting", "msgs": ["hey, what's new"]},
    {"id": 49, "tag": "greeting", "msgs": ["anyone there?"]},
    {"id": 50, "tag": "greeting", "msgs": ["knock knock"]},

    # ═══════════════════════════════════════════════════════════════════════
    # IDENTITY — who are you, what can you do (51-80)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 51, "tag": "identity", "msgs": ["who are you"]},
    {"id": 52, "tag": "identity", "msgs": ["what are you"]},
    {"id": 53, "tag": "identity", "msgs": ["what's your name"]},
    {"id": 54, "tag": "identity", "msgs": ["what can you do"]},
    {"id": 55, "tag": "identity", "msgs": ["what are your capabilities"]},
    {"id": 56, "tag": "identity", "msgs": ["help me"]},
    {"id": 57, "tag": "identity", "msgs": ["what do you do"]},
    {"id": 58, "tag": "identity", "msgs": ["who am I"]},
    {"id": 59, "tag": "identity", "msgs": ["what do you know about me"]},
    {"id": 60, "tag": "identity", "msgs": ["do you remember me"]},
    {"id": 61, "tag": "identity", "msgs": ["what's my name"]},
    {"id": 62, "tag": "identity", "msgs": ["tell me about yourself"]},
    {"id": 63, "tag": "identity", "msgs": ["introduce yourself"]},
    {"id": 64, "tag": "identity", "msgs": ["how were you built"]},
    {"id": 65, "tag": "identity", "msgs": ["what tools do you have"]},
    {"id": 66, "tag": "identity", "msgs": ["show me your nerves"]},
    {"id": 67, "tag": "identity", "msgs": ["what senses do you have"]},
    {"id": 68, "tag": "identity", "msgs": ["how many nerves do you have"]},
    {"id": 69, "tag": "identity", "msgs": ["what's your status"]},
    {"id": 70, "tag": "identity", "msgs": ["are you alive"]},
    {"id": 71, "tag": "identity", "msgs": ["are you sentient"]},
    {"id": 72, "tag": "identity", "msgs": ["what makes you different from ChatGPT"]},
    {"id": 73, "tag": "identity", "msgs": ["what are your limits"]},
    {"id": 74, "tag": "identity", "msgs": ["what can't you do"]},
    {"id": 75, "tag": "identity", "msgs": ["are you an AI"]},
    {"id": 76, "tag": "identity", "msgs": ["what model do you use"]},
    {"id": 77, "tag": "identity", "msgs": ["how do you learn"]},
    {"id": 78, "tag": "identity", "msgs": ["do you have feelings"]},
    {"id": 79, "tag": "identity", "msgs": ["what's your architecture"]},
    {"id": 80, "tag": "identity", "msgs": ["can you see and hear"]},

    # ═══════════════════════════════════════════════════════════════════════
    # KNOWLEDGE — general knowledge questions (81-180)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 81, "tag": "knowledge", "msgs": ["what is photosynthesis"]},
    {"id": 82, "tag": "knowledge", "msgs": ["who invented the telephone"]},
    {"id": 83, "tag": "knowledge", "msgs": ["what is the speed of light"]},
    {"id": 84, "tag": "knowledge", "msgs": ["how tall is mount everest"]},
    {"id": 85, "tag": "knowledge", "msgs": ["what is the capital of France"]},
    {"id": 86, "tag": "knowledge", "msgs": ["what is the largest ocean"]},
    {"id": 87, "tag": "knowledge", "msgs": ["who wrote Romeo and Juliet"]},
    {"id": 88, "tag": "knowledge", "msgs": ["what year did World War 2 end"]},
    {"id": 89, "tag": "knowledge", "msgs": ["what is DNA"]},
    {"id": 90, "tag": "knowledge", "msgs": ["how does gravity work"]},
    {"id": 91, "tag": "knowledge", "msgs": ["what is the theory of relativity"]},
    {"id": 92, "tag": "knowledge", "msgs": ["who was Albert Einstein"]},
    {"id": 93, "tag": "knowledge", "msgs": ["what causes earthquakes"]},
    {"id": 94, "tag": "knowledge", "msgs": ["how do planes fly"]},
    {"id": 95, "tag": "knowledge", "msgs": ["what is blockchain"]},
    {"id": 96, "tag": "knowledge", "msgs": ["explain quantum computing"]},
    {"id": 97, "tag": "knowledge", "msgs": ["what is machine learning"]},
    {"id": 98, "tag": "knowledge", "msgs": ["how does the internet work"]},
    {"id": 99, "tag": "knowledge", "msgs": ["what is a black hole"]},
    {"id": 100, "tag": "knowledge", "msgs": ["who discovered penicillin"]},
    {"id": 101, "tag": "knowledge", "msgs": ["what is the Pythagorean theorem"]},
    {"id": 102, "tag": "knowledge", "msgs": ["what are prime numbers"]},
    {"id": 103, "tag": "knowledge", "msgs": ["explain the water cycle"]},
    {"id": 104, "tag": "knowledge", "msgs": ["what is the periodic table"]},
    {"id": 105, "tag": "knowledge", "msgs": ["how do vaccines work"]},
    {"id": 106, "tag": "knowledge", "msgs": ["what is the greenhouse effect"]},
    {"id": 107, "tag": "knowledge", "msgs": ["who painted the Mona Lisa"]},
    {"id": 108, "tag": "knowledge", "msgs": ["what is the Fibonacci sequence"]},
    {"id": 109, "tag": "knowledge", "msgs": ["how do computers store data"]},
    {"id": 110, "tag": "knowledge", "msgs": ["what is TCP/IP"]},
    {"id": 111, "tag": "knowledge", "msgs": ["explain the big bang theory"]},
    {"id": 112, "tag": "knowledge", "msgs": ["what is evolution"]},
    {"id": 113, "tag": "knowledge", "msgs": ["how does electricity work"]},
    {"id": 114, "tag": "knowledge", "msgs": ["what is a neural network"]},
    {"id": 115, "tag": "knowledge", "msgs": ["who was Nikola Tesla"]},
    {"id": 116, "tag": "knowledge", "msgs": ["what is the human genome"]},
    {"id": 117, "tag": "knowledge", "msgs": ["explain the stock market"]},
    {"id": 118, "tag": "knowledge", "msgs": ["what is inflation"]},
    {"id": 119, "tag": "knowledge", "msgs": ["how does a car engine work"]},
    {"id": 120, "tag": "knowledge", "msgs": ["what is the solar system"]},
    {"id": 121, "tag": "knowledge", "msgs": ["what are tectonic plates"]},
    {"id": 122, "tag": "knowledge", "msgs": ["how do batteries work"]},
    {"id": 123, "tag": "knowledge", "msgs": ["what is CRISPR"]},
    {"id": 124, "tag": "knowledge", "msgs": ["explain supply and demand"]},
    {"id": 125, "tag": "knowledge", "msgs": ["what is the speed of sound"]},
    {"id": 126, "tag": "knowledge", "msgs": ["who discovered America"]},
    {"id": 127, "tag": "knowledge", "msgs": ["what is the Turing test"]},
    {"id": 128, "tag": "knowledge", "msgs": ["how does Wi-Fi work"]},
    {"id": 129, "tag": "knowledge", "msgs": ["what is GDP"]},
    {"id": 130, "tag": "knowledge", "msgs": ["explain the doppler effect"]},
    {"id": 131, "tag": "knowledge", "msgs": ["what is an algorithm"]},
    {"id": 132, "tag": "knowledge", "msgs": ["how do magnets work"]},
    {"id": 133, "tag": "knowledge", "msgs": ["what is the Rosetta Stone"]},
    {"id": 134, "tag": "knowledge", "msgs": ["who built the pyramids"]},
    {"id": 135, "tag": "knowledge", "msgs": ["what is dark matter"]},
    {"id": 136, "tag": "knowledge", "msgs": ["how deep is the Mariana Trench"]},
    {"id": 137, "tag": "knowledge", "msgs": ["what is the Hubble telescope"]},
    {"id": 138, "tag": "knowledge", "msgs": ["explain the Doppler effect"]},
    {"id": 139, "tag": "knowledge", "msgs": ["what is stoicism"]},
    {"id": 140, "tag": "knowledge", "msgs": ["who was Aristotle"]},
    {"id": 141, "tag": "knowledge", "msgs": ["what is the renaissance"]},
    {"id": 142, "tag": "knowledge", "msgs": ["how does a microprocessor work"]},
    {"id": 143, "tag": "knowledge", "msgs": ["what is the difference between RAM and ROM"]},
    {"id": 144, "tag": "knowledge", "msgs": ["explain the scientific method"]},
    {"id": 145, "tag": "knowledge", "msgs": ["what is the Milky Way"]},
    {"id": 146, "tag": "knowledge", "msgs": ["how many planets are in our solar system"]},
    {"id": 147, "tag": "knowledge", "msgs": ["what is the population of Earth"]},
    {"id": 148, "tag": "knowledge", "msgs": ["who was Marie Curie"]},
    {"id": 149, "tag": "knowledge", "msgs": ["what is the Amazon rainforest"]},
    {"id": 150, "tag": "knowledge", "msgs": ["explain the butterfly effect"]},
    {"id": 151, "tag": "knowledge", "msgs": ["what is the difference between a virus and bacteria"]},
    {"id": 152, "tag": "knowledge", "msgs": ["what is the Great Wall of China"]},
    {"id": 153, "tag": "knowledge", "msgs": ["how do lasers work"]},
    {"id": 154, "tag": "knowledge", "msgs": ["what is cryptocurrency"]},
    {"id": 155, "tag": "knowledge", "msgs": ["explain the concept of entropy"]},
    {"id": 156, "tag": "knowledge", "msgs": ["what is the Heisenberg uncertainty principle"]},
    {"id": 157, "tag": "knowledge", "msgs": ["how does GPS work"]},
    {"id": 158, "tag": "knowledge", "msgs": ["what is the UN"]},
    {"id": 159, "tag": "knowledge", "msgs": ["what caused the French Revolution"]},
    {"id": 160, "tag": "knowledge", "msgs": ["how does nuclear energy work"]},
    {"id": 161, "tag": "knowledge", "msgs": ["what is the Krebs cycle"]},
    {"id": 162, "tag": "knowledge", "msgs": ["explain photovoltaic cells"]},
    {"id": 163, "tag": "knowledge", "msgs": ["what is the difference between weather and climate"]},
    {"id": 164, "tag": "knowledge", "msgs": ["who was Leonardo da Vinci"]},
    {"id": 165, "tag": "knowledge", "msgs": ["what is the hippocratic oath"]},
    {"id": 166, "tag": "knowledge", "msgs": ["how do submarines work"]},
    {"id": 167, "tag": "knowledge", "msgs": ["what is the Silk Road"]},
    {"id": 168, "tag": "knowledge", "msgs": ["explain the concept of infinity"]},
    {"id": 169, "tag": "knowledge", "msgs": ["what is a supernova"]},
    {"id": 170, "tag": "knowledge", "msgs": ["how does sonar work"]},
    {"id": 171, "tag": "knowledge", "msgs": ["what is the Geneva Convention"]},
    {"id": 172, "tag": "knowledge", "msgs": ["explain Moore's law"]},
    {"id": 173, "tag": "knowledge", "msgs": ["what is the Richter scale"]},
    {"id": 174, "tag": "knowledge", "msgs": ["how does a telescope work"]},
    {"id": 175, "tag": "knowledge", "msgs": ["what is the International Space Station"]},
    {"id": 176, "tag": "knowledge", "msgs": ["who was Cleopatra"]},
    {"id": 177, "tag": "knowledge", "msgs": ["what are stem cells"]},
    {"id": 178, "tag": "knowledge", "msgs": ["explain Occam's razor"]},
    {"id": 179, "tag": "knowledge", "msgs": ["what is the Dead Sea"]},
    {"id": 180, "tag": "knowledge", "msgs": ["how does 3D printing work"]},

    # ═══════════════════════════════════════════════════════════════════════
    # FUN — jokes, riddles, creative tasks (181-230)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 181, "tag": "fun", "msgs": ["tell me a joke"]},
    {"id": 182, "tag": "fun", "msgs": ["tell me a funny joke"]},
    {"id": 183, "tag": "fun", "msgs": ["give me a dad joke"]},
    {"id": 184, "tag": "fun", "msgs": ["tell me a programming joke"]},
    {"id": 185, "tag": "fun", "msgs": ["tell me a science joke"]},
    {"id": 186, "tag": "fun", "msgs": ["give me a riddle"]},
    {"id": 187, "tag": "fun", "msgs": ["give me a hard riddle"]},
    {"id": 188, "tag": "fun", "msgs": ["tell me a tongue twister"]},
    {"id": 189, "tag": "fun", "msgs": ["give me another tongue twister"]},
    {"id": 190, "tag": "fun", "msgs": ["write me a short poem"]},
    {"id": 191, "tag": "fun", "msgs": ["write a haiku about coding"]},
    {"id": 192, "tag": "fun", "msgs": ["write a limerick about computers"]},
    {"id": 193, "tag": "fun", "msgs": ["tell me a fun fact"]},
    {"id": 194, "tag": "fun", "msgs": ["give me a random fact"]},
    {"id": 195, "tag": "fun", "msgs": ["tell me something interesting"]},
    {"id": 196, "tag": "fun", "msgs": ["make me laugh"]},
    {"id": 197, "tag": "fun", "msgs": ["tell me a knock knock joke"]},
    {"id": 198, "tag": "fun", "msgs": ["write a short story about a robot"]},
    {"id": 199, "tag": "fun", "msgs": ["give me a brain teaser"]},
    {"id": 200, "tag": "fun", "msgs": ["what's a fun fact about space"]},
    {"id": 201, "tag": "fun", "msgs": ["write a poem about the moon"]},
    {"id": 202, "tag": "fun", "msgs": ["tell me a joke about JavaScript"]},
    {"id": 203, "tag": "fun", "msgs": ["give me a math riddle"]},
    {"id": 204, "tag": "fun", "msgs": ["write a haiku about nature"]},
    {"id": 205, "tag": "fun", "msgs": ["tell me a joke about AI"]},
    {"id": 206, "tag": "fun", "msgs": ["give me a word puzzle"]},
    {"id": 207, "tag": "fun", "msgs": ["what's a fun fact about the ocean"]},
    {"id": 208, "tag": "fun", "msgs": ["write a short poem about coffee"]},
    {"id": 209, "tag": "fun", "msgs": ["tell me an animal fact"]},
    {"id": 210, "tag": "fun", "msgs": ["give me a logic puzzle"]},
    {"id": 211, "tag": "fun", "msgs": ["tell me a history fun fact"]},
    {"id": 212, "tag": "fun", "msgs": ["write a tongue twister about turtles"]},
    {"id": 213, "tag": "fun", "msgs": ["give me a number puzzle"]},
    {"id": 214, "tag": "fun", "msgs": ["tell me a joke about cats"]},
    {"id": 215, "tag": "fun", "msgs": ["write a limerick about pizza"]},
    {"id": 216, "tag": "fun", "msgs": ["give me a trivia question"]},
    {"id": 217, "tag": "fun", "msgs": ["tell me a joke in one line"]},
    {"id": 218, "tag": "fun", "msgs": ["write a poem about friendship"]},
    {"id": 219, "tag": "fun", "msgs": ["tell me a dark humor joke"]},
    {"id": 220, "tag": "fun", "msgs": ["give me a riddle about time"]},
    {"id": 221, "tag": "fun", "msgs": ["write a haiku about rain"]},
    {"id": 222, "tag": "fun", "msgs": ["tell me a joke about databases"]},
    {"id": 223, "tag": "fun", "msgs": ["give me a philosophical riddle"]},
    {"id": 224, "tag": "fun", "msgs": ["write a short poem about sunrise"]},
    {"id": 225, "tag": "fun", "msgs": ["tell me a clean joke for kids"]},
    {"id": 226, "tag": "fun", "msgs": ["give me a creative writing prompt"]},
    {"id": 227, "tag": "fun", "msgs": ["write a story in exactly 6 words"]},
    {"id": 228, "tag": "fun", "msgs": ["tell me a pun"]},
    {"id": 229, "tag": "fun", "msgs": ["give me a tongue twister in English"]},
    {"id": 230, "tag": "fun", "msgs": ["write an acrostic poem for PYTHON"]},

    # ═══════════════════════════════════════════════════════════════════════
    # WEATHER — weather queries (231-270)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 231, "tag": "weather", "msgs": ["what's the weather today"]},
    {"id": 232, "tag": "weather", "msgs": ["what is the weather in Tel Aviv"]},
    {"id": 233, "tag": "weather", "msgs": ["what's the forecast for today"]},
    {"id": 234, "tag": "weather", "msgs": ["will it rain today"]},
    {"id": 235, "tag": "weather", "msgs": ["is it going to be hot today"]},
    {"id": 236, "tag": "weather", "msgs": ["what's the temperature outside"]},
    {"id": 237, "tag": "weather", "msgs": ["weather in New York"]},
    {"id": 238, "tag": "weather", "msgs": ["what's the weather like in London"]},
    {"id": 239, "tag": "weather", "msgs": ["is it cold in Moscow right now"]},
    {"id": 240, "tag": "weather", "msgs": ["weather forecast for Tokyo"]},
    {"id": 241, "tag": "weather", "msgs": ["do I need an umbrella today"]},
    {"id": 242, "tag": "weather", "msgs": ["what should I wear today"]},
    {"id": 243, "tag": "weather", "msgs": ["weather in Paris this week"]},
    {"id": 244, "tag": "weather", "msgs": ["is it sunny in Los Angeles"]},
    {"id": 245, "tag": "weather", "msgs": ["what's the humidity today"]},
    {"id": 246, "tag": "weather", "msgs": ["will there be a storm today"]},
    {"id": 247, "tag": "weather", "msgs": ["weather in Jerusalem"]},
    {"id": 248, "tag": "weather", "msgs": ["what's the wind speed right now"]},
    {"id": 249, "tag": "weather", "msgs": ["temperature in Berlin"]},
    {"id": 250, "tag": "weather", "msgs": ["is it snowing in Denver"]},
    {"id": 251, "tag": "weather", "msgs": ["weather in Rishon LeZion"]},
    {"id": 252, "tag": "weather", "msgs": ["what's the UV index today"]},
    {"id": 253, "tag": "weather", "msgs": ["forecast for the weekend"]},
    {"id": 254, "tag": "weather", "msgs": ["how hot is it in Dubai"]},
    {"id": 255, "tag": "weather", "msgs": ["weather in San Francisco"]},
    {"id": 256, "tag": "weather", "msgs": ["will it be cloudy tomorrow"]},
    {"id": 257, "tag": "weather", "msgs": ["what's the weather in Sydney"]},
    {"id": 258, "tag": "weather", "msgs": ["is it raining in Seattle"]},
    {"id": 259, "tag": "weather", "msgs": ["current weather conditions"]},
    {"id": 260, "tag": "weather", "msgs": ["weather in Haifa"]},
    {"id": 261, "tag": "weather", "msgs": ["should I bring a jacket"]},
    {"id": 262, "tag": "weather", "msgs": ["weather in Eilat"]},
    {"id": 263, "tag": "weather", "msgs": ["is it a good day for the beach"]},
    {"id": 264, "tag": "weather", "msgs": ["what's the air quality today"]},
    {"id": 265, "tag": "weather", "msgs": ["weather in Amsterdam"]},
    {"id": 266, "tag": "weather", "msgs": ["temperature in Rome"]},
    {"id": 267, "tag": "weather", "msgs": ["weather in Singapore"]},
    {"id": 268, "tag": "weather", "msgs": ["is it windy today"]},
    {"id": 269, "tag": "weather", "msgs": ["weather in Istanbul"]},
    {"id": 270, "tag": "weather", "msgs": ["what's the weather near me"]},

    # ═══════════════════════════════════════════════════════════════════════
    # MATH — calculations, conversions, math problems (271-340)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 271, "tag": "math", "msgs": ["what is 2 + 2"]},
    {"id": 272, "tag": "math", "msgs": ["calculate 15 * 27"]},
    {"id": 273, "tag": "math", "msgs": ["what is 144 / 12"]},
    {"id": 274, "tag": "math", "msgs": ["what is the square root of 256"]},
    {"id": 275, "tag": "math", "msgs": ["calculate 2^10"]},
    {"id": 276, "tag": "math", "msgs": ["what is 17% of 350"]},
    {"id": 277, "tag": "math", "msgs": ["solve x^2 - 5x + 6 = 0"]},
    {"id": 278, "tag": "math", "msgs": ["what is the factorial of 10"]},
    {"id": 279, "tag": "math", "msgs": ["calculate the area of a circle with radius 7"]},
    {"id": 280, "tag": "math", "msgs": ["convert 100 kilometers to miles"]},
    {"id": 281, "tag": "math", "msgs": ["convert 72 fahrenheit to celsius"]},
    {"id": 282, "tag": "math", "msgs": ["how many inches in a meter"]},
    {"id": 283, "tag": "math", "msgs": ["convert 5 pounds to kilograms"]},
    {"id": 284, "tag": "math", "msgs": ["what is 1000 USD in EUR"]},
    {"id": 285, "tag": "math", "msgs": ["convert 500 USD to ILS"]},
    {"id": 286, "tag": "math", "msgs": ["what is the GCD of 48 and 36"]},
    {"id": 287, "tag": "math", "msgs": ["is 97 a prime number"]},
    {"id": 288, "tag": "math", "msgs": ["what are the first 20 prime numbers"]},
    {"id": 289, "tag": "math", "msgs": ["calculate the fibonacci of 15"]},
    {"id": 290, "tag": "math", "msgs": ["what is sin(45 degrees)"]},
    {"id": 291, "tag": "math", "msgs": ["calculate log base 2 of 1024"]},
    {"id": 292, "tag": "math", "msgs": ["what is the derivative of x^3"]},
    {"id": 293, "tag": "math", "msgs": ["integrate 2x dx"]},
    {"id": 294, "tag": "math", "msgs": ["solve 3x + 7 = 22"]},
    {"id": 295, "tag": "math", "msgs": ["what is the LCM of 12 and 18"]},
    {"id": 296, "tag": "math", "msgs": ["calculate 999 * 999"]},
    {"id": 297, "tag": "math", "msgs": ["what is e^2"]},
    {"id": 298, "tag": "math", "msgs": ["convert 1 light year to kilometers"]},
    {"id": 299, "tag": "math", "msgs": ["what is the volume of a sphere with radius 5"]},
    {"id": 300, "tag": "math", "msgs": ["calculate the hypotenuse of a 3-4-5 triangle"]},
    {"id": 301, "tag": "math", "msgs": ["what is 3! + 4!"]},
    {"id": 302, "tag": "math", "msgs": ["how many seconds in a year"]},
    {"id": 303, "tag": "math", "msgs": ["what is pi to 10 decimal places"]},
    {"id": 304, "tag": "math", "msgs": ["calculate BMI for 80kg and 1.75m"]},
    {"id": 305, "tag": "math", "msgs": ["what is 0.1 + 0.2"]},
    {"id": 306, "tag": "math", "msgs": ["convert 1 gallon to liters"]},
    {"id": 307, "tag": "math", "msgs": ["how many bytes in a gigabyte"]},
    {"id": 308, "tag": "math", "msgs": ["what is the sum of numbers 1 to 100"]},
    {"id": 309, "tag": "math", "msgs": ["convert binary 11010101 to decimal"]},
    {"id": 310, "tag": "math", "msgs": ["what is hex FF in decimal"]},
    {"id": 311, "tag": "math", "msgs": ["calculate compound interest on $1000 at 5% for 10 years"]},
    {"id": 312, "tag": "math", "msgs": ["what is the standard deviation of 2, 4, 4, 4, 5, 5, 7, 9"]},
    {"id": 313, "tag": "math", "msgs": ["solve the quadratic x^2 + 4x - 5 = 0"]},
    {"id": 314, "tag": "math", "msgs": ["what is cos(60 degrees)"]},
    {"id": 315, "tag": "math", "msgs": ["convert 90 degrees to radians"]},
    {"id": 316, "tag": "math", "msgs": ["what is 2 to the power of 32"]},
    {"id": 317, "tag": "math", "msgs": ["what is the median of 1, 3, 5, 7, 9, 11"]},
    {"id": 318, "tag": "math", "msgs": ["how many combinations of 5 items from 10"]},
    {"id": 319, "tag": "math", "msgs": ["what is the matrix determinant of [[1,2],[3,4]]"]},
    {"id": 320, "tag": "math", "msgs": ["simplify the fraction 48/64"]},
    {"id": 321, "tag": "math", "msgs": ["convert 25 celsius to fahrenheit"]},
    {"id": 322, "tag": "math", "msgs": ["what is the perimeter of a rectangle 5 by 8"]},
    {"id": 323, "tag": "math", "msgs": ["calculate tip: 15% on a $85 bill"]},
    {"id": 324, "tag": "math", "msgs": ["convert 200 GBP to USD"]},
    {"id": 325, "tag": "math", "msgs": ["what is 1 million divided by 7"]},
    {"id": 326, "tag": "math", "msgs": ["how many days until new year"]},
    {"id": 327, "tag": "math", "msgs": ["what day of the week was January 1, 2000"]},
    {"id": 328, "tag": "math", "msgs": ["convert 10 nautical miles to kilometers"]},
    {"id": 329, "tag": "math", "msgs": ["calculate the slope between (2,3) and (5,11)"]},
    {"id": 330, "tag": "math", "msgs": ["what is the distance between (0,0) and (3,4)"]},
    {"id": 331, "tag": "math", "msgs": ["sort these numbers: 45, 12, 78, 3, 56, 21"]},
    {"id": 332, "tag": "math", "msgs": ["what is the average of 85, 90, 78, 92, 88"]},
    {"id": 333, "tag": "math", "msgs": ["convert 1 troy ounce to grams"]},
    {"id": 334, "tag": "math", "msgs": ["what is the circumference of a circle with diameter 10"]},
    {"id": 335, "tag": "math", "msgs": ["solve: if a train travels 120km in 2 hours, what's its speed"]},
    {"id": 336, "tag": "math", "msgs": ["how many permutations of the letters in HELLO"]},
    {"id": 337, "tag": "math", "msgs": ["what is absolute value of -42"]},
    {"id": 338, "tag": "math", "msgs": ["convert 1 bar to PSI"]},
    {"id": 339, "tag": "math", "msgs": ["calculate the area of a triangle with base 10 and height 6"]},
    {"id": 340, "tag": "math", "msgs": ["what is the remainder of 100 divided by 7"]},

    # ═══════════════════════════════════════════════════════════════════════
    # PRODUCTIVITY — scheduling, planning, organizing (341-410)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 341, "tag": "productivity", "msgs": ["create a daily schedule for a software developer"]},
    {"id": 342, "tag": "productivity", "msgs": ["plan my morning routine"]},
    {"id": 343, "tag": "productivity", "msgs": ["set a timer for 5 minutes"]},
    {"id": 344, "tag": "productivity", "msgs": ["remind me to call mom at 6pm"]},
    {"id": 345, "tag": "productivity", "msgs": ["schedule a meeting for tomorrow at 10am"]},
    {"id": 346, "tag": "productivity", "msgs": ["what's on my calendar today"]},
    {"id": 347, "tag": "productivity", "msgs": ["create a todo list for a house move"]},
    {"id": 348, "tag": "productivity", "msgs": ["plan a weekly meal prep schedule"]},
    {"id": 349, "tag": "productivity", "msgs": ["organize my tasks by priority"]},
    {"id": 350, "tag": "productivity", "msgs": ["create a project timeline for launching a website"]},
    {"id": 351, "tag": "productivity", "msgs": ["what time is it in New York"]},
    {"id": 352, "tag": "productivity", "msgs": ["what time is it in Tokyo"]},
    {"id": 353, "tag": "productivity", "msgs": ["convert 3pm EST to Israel time"]},
    {"id": 354, "tag": "productivity", "msgs": ["set a timer for 25 minutes (pomodoro)"]},
    {"id": 355, "tag": "productivity", "msgs": ["create a study plan for learning Python"]},
    {"id": 356, "tag": "productivity", "msgs": ["plan a sprint for a 2-week development cycle"]},
    {"id": 357, "tag": "productivity", "msgs": ["create a checklist for deploying a web app"]},
    {"id": 358, "tag": "productivity", "msgs": ["organize these tasks: fix bug, write tests, deploy, code review"]},
    {"id": 359, "tag": "productivity", "msgs": ["create a meeting agenda for a standup"]},
    {"id": 360, "tag": "productivity", "msgs": ["plan a birthday party"]},
    {"id": 361, "tag": "productivity", "msgs": ["create a packing list for a business trip"]},
    {"id": 362, "tag": "productivity", "msgs": ["schedule a code review session"]},
    {"id": 363, "tag": "productivity", "msgs": ["plan a workout routine for the week"]},
    {"id": 364, "tag": "productivity", "msgs": ["create a budget for a small project"]},
    {"id": 365, "tag": "productivity", "msgs": ["organize my reading list"]},
    {"id": 366, "tag": "productivity", "msgs": ["plan a team building activity"]},
    {"id": 367, "tag": "productivity", "msgs": ["create a retrospective template"]},
    {"id": 368, "tag": "productivity", "msgs": ["schedule recurring daily standup at 9:30am"]},
    {"id": 369, "tag": "productivity", "msgs": ["plan a product roadmap for Q1"]},
    {"id": 370, "tag": "productivity", "msgs": ["create an onboarding checklist for new developers"]},
    {"id": 371, "tag": "productivity", "msgs": ["schedule a dentist appointment"]},
    {"id": 372, "tag": "productivity", "msgs": ["plan a weekend trip to the beach"]},
    {"id": 373, "tag": "productivity", "msgs": ["create a grocery list"]},
    {"id": 374, "tag": "productivity", "msgs": ["plan a date night"]},
    {"id": 375, "tag": "productivity", "msgs": ["organize my photos"]},
    {"id": 376, "tag": "productivity", "msgs": ["create a fitness plan for beginners"]},
    {"id": 377, "tag": "productivity", "msgs": ["plan a garden layout"]},
    {"id": 378, "tag": "productivity", "msgs": ["schedule a car service"]},
    {"id": 379, "tag": "productivity", "msgs": ["create a cleaning schedule for the house"]},
    {"id": 380, "tag": "productivity", "msgs": ["plan a presentation for Monday"]},
    {"id": 381, "tag": "productivity", "msgs": ["create a habit tracker"]},
    {"id": 382, "tag": "productivity", "msgs": ["plan my day: I have 3 meetings and need to finish a report"]},
    {"id": 383, "tag": "productivity", "msgs": ["create a travel itinerary for 3 days in Berlin"]},
    {"id": 384, "tag": "productivity", "msgs": ["organize my bookmarks"]},
    {"id": 385, "tag": "productivity", "msgs": ["plan a hackathon event"]},
    {"id": 386, "tag": "productivity", "msgs": ["create a decision matrix for choosing a new laptop"]},
    {"id": 387, "tag": "productivity", "msgs": ["schedule all my meetings for next week"]},
    {"id": 388, "tag": "productivity", "msgs": ["plan a content calendar for social media"]},
    {"id": 389, "tag": "productivity", "msgs": ["create a risk assessment for a software project"]},
    {"id": 390, "tag": "productivity", "msgs": ["plan a workshop on Git basics"]},
    {"id": 391, "tag": "productivity", "msgs": ["create an interview preparation plan"]},
    {"id": 392, "tag": "productivity", "msgs": ["plan a release cycle for a mobile app"]},
    {"id": 393, "tag": "productivity", "msgs": ["organize my music playlist by mood"]},
    {"id": 394, "tag": "productivity", "msgs": ["create a savings plan for a vacation"]},
    {"id": 395, "tag": "productivity", "msgs": ["plan a tech talk about microservices"]},
    {"id": 396, "tag": "productivity", "msgs": ["create a learning path for machine learning"]},
    {"id": 397, "tag": "productivity", "msgs": ["schedule a quarterly review meeting"]},
    {"id": 398, "tag": "productivity", "msgs": ["plan a migration from monolith to microservices"]},
    {"id": 399, "tag": "productivity", "msgs": ["create a KPI dashboard plan"]},
    {"id": 400, "tag": "productivity", "msgs": ["plan a team lunch for 10 people"]},
    {"id": 401, "tag": "productivity", "msgs": ["create a disaster recovery plan"]},
    {"id": 402, "tag": "productivity", "msgs": ["schedule a vet appointment for my cat"]},
    {"id": 403, "tag": "productivity", "msgs": ["plan a book club meeting"]},
    {"id": 404, "tag": "productivity", "msgs": ["create a renovation timeline"]},
    {"id": 405, "tag": "productivity", "msgs": ["organize my email inbox strategy"]},
    {"id": 406, "tag": "productivity", "msgs": ["plan a potluck dinner"]},
    {"id": 407, "tag": "productivity", "msgs": ["create a morning affirmations list"]},
    {"id": 408, "tag": "productivity", "msgs": ["schedule a photography session"]},
    {"id": 409, "tag": "productivity", "msgs": ["plan a volunteer event"]},
    {"id": 410, "tag": "productivity", "msgs": ["create a self-care routine"]},

    # ═══════════════════════════════════════════════════════════════════════
    # WRITING — summarize, format, rewrite (411-460)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 411, "tag": "writing", "msgs": ["summarize the concept of machine learning in 3 sentences"]},
    {"id": 412, "tag": "writing", "msgs": ["rewrite this formally: hey dude, the server is down again"]},
    {"id": 413, "tag": "writing", "msgs": ["write a professional email declining a meeting"]},
    {"id": 414, "tag": "writing", "msgs": ["write a commit message for: fixed login page redirect bug"]},
    {"id": 415, "tag": "writing", "msgs": ["write a PR description for adding dark mode support"]},
    {"id": 416, "tag": "writing", "msgs": ["write a user story for a search feature"]},
    {"id": 417, "tag": "writing", "msgs": ["summarize the benefits of TypeScript over JavaScript"]},
    {"id": 418, "tag": "writing", "msgs": ["write a bug report template"]},
    {"id": 419, "tag": "writing", "msgs": ["rewrite this casually: We regret to inform you that your application has been unsuccessful"]},
    {"id": 420, "tag": "writing", "msgs": ["write a README intro for a weather API project"]},
    {"id": 421, "tag": "writing", "msgs": ["write a Slack message announcing a new feature release"]},
    {"id": 422, "tag": "writing", "msgs": ["summarize REST vs GraphQL"]},
    {"id": 423, "tag": "writing", "msgs": ["write a cover letter for a senior developer position"]},
    {"id": 424, "tag": "writing", "msgs": ["rewrite this for a non-technical audience: The API returns a 503 due to upstream timeout"]},
    {"id": 425, "tag": "writing", "msgs": ["write documentation for a login function"]},
    {"id": 426, "tag": "writing", "msgs": ["create a changelog entry for version 2.1.0"]},
    {"id": 427, "tag": "writing", "msgs": ["write a tweet about a new open source project"]},
    {"id": 428, "tag": "writing", "msgs": ["summarize agile methodology"]},
    {"id": 429, "tag": "writing", "msgs": ["write an incident report for a database outage"]},
    {"id": 430, "tag": "writing", "msgs": ["rewrite this more concisely: In order to be able to successfully complete the process of authentication, users are required to provide both their username and their password"]},
    {"id": 431, "tag": "writing", "msgs": ["write a project proposal for a mobile app"]},
    {"id": 432, "tag": "writing", "msgs": ["create a FAQ section for a SaaS product"]},
    {"id": 433, "tag": "writing", "msgs": ["write a thank you note to a mentor"]},
    {"id": 434, "tag": "writing", "msgs": ["summarize the SOLID principles"]},
    {"id": 435, "tag": "writing", "msgs": ["write a job description for a full-stack developer"]},
    {"id": 436, "tag": "writing", "msgs": ["create a glossary of DevOps terms"]},
    {"id": 437, "tag": "writing", "msgs": ["write an API documentation for a GET /users endpoint"]},
    {"id": 438, "tag": "writing", "msgs": ["summarize the difference between SQL and NoSQL"]},
    {"id": 439, "tag": "writing", "msgs": ["write a technical blog post outline about React hooks"]},
    {"id": 440, "tag": "writing", "msgs": ["rewrite this email to be shorter: Dear valued customer, I hope this email finds you well. I am writing to you today to inform you that we have recently updated our terms of service and privacy policy"]},
    {"id": 441, "tag": "writing", "msgs": ["write a product description for a smart watch"]},
    {"id": 442, "tag": "writing", "msgs": ["create a comparison table: React vs Vue vs Angular"]},
    {"id": 443, "tag": "writing", "msgs": ["write a bio for a developer portfolio"]},
    {"id": 444, "tag": "writing", "msgs": ["summarize Docker in simple terms"]},
    {"id": 445, "tag": "writing", "msgs": ["write a workshop description for an intro to Python course"]},
    {"id": 446, "tag": "writing", "msgs": ["create an executive summary for a data analytics project"]},
    {"id": 447, "tag": "writing", "msgs": ["write a LinkedIn recommendation for a colleague"]},
    {"id": 448, "tag": "writing", "msgs": ["summarize the CAP theorem"]},
    {"id": 449, "tag": "writing", "msgs": ["write a press release for a startup launch"]},
    {"id": 450, "tag": "writing", "msgs": ["create talking points for a tech conference"]},
    {"id": 451, "tag": "writing", "msgs": ["write an apology email for a service disruption"]},
    {"id": 452, "tag": "writing", "msgs": ["summarize what a microservice architecture is"]},
    {"id": 453, "tag": "writing", "msgs": ["write a congratulations message for a promotion"]},
    {"id": 454, "tag": "writing", "msgs": ["create a tech spec for a caching layer"]},
    {"id": 455, "tag": "writing", "msgs": ["write acceptance criteria for a login feature"]},
    {"id": 456, "tag": "writing", "msgs": ["summarize the benefits of CI/CD"]},
    {"id": 457, "tag": "writing", "msgs": ["write a postmortem template"]},
    {"id": 458, "tag": "writing", "msgs": ["create a feature comparison: Kubernetes vs Docker Swarm"]},
    {"id": 459, "tag": "writing", "msgs": ["write a welcome message for a Slack workspace"]},
    {"id": 460, "tag": "writing", "msgs": ["summarize what WebSockets are and when to use them"]},

    # ═══════════════════════════════════════════════════════════════════════
    # CODE-PYTHON — Project analysis & Python questions (461-560)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 461, "tag": "code-python", "msgs": ["in the stocky project, how does the ingest pipeline handle historical data"]},
    {"id": 462, "tag": "code-python", "msgs": ["explain the feature engineering approach in stocky's features module"]},
    {"id": 463, "tag": "code-python", "msgs": ["what database schema does stocky use for storing price data"]},
    {"id": 464, "tag": "code-python", "msgs": ["how does stocky use TimescaleDB hypertables for time-series data"]},
    {"id": 465, "tag": "code-python", "msgs": ["review the stocky CLI commands — what Typer commands are available"]},
    {"id": 466, "tag": "code-python", "msgs": ["how does stocky's labeling module generate training labels from price data"]},
    {"id": 467, "tag": "code-python", "msgs": ["what machine learning models does stocky use for prediction"]},
    {"id": 468, "tag": "code-python", "msgs": ["explain how stocky uses xgboost for stock prediction"]},
    {"id": 469, "tag": "code-python", "msgs": ["how does stocky handle Alembic database migrations"]},
    {"id": 470, "tag": "code-python", "msgs": ["what technical indicators does stocky compute using ta-lib"]},
    {"id": 471, "tag": "code-python", "msgs": ["how does stocky fetch data from yfinance for TA-100 stocks"]},
    {"id": 472, "tag": "code-python", "msgs": ["explain stocky's simulation module — how does backtesting work"]},
    {"id": 473, "tag": "code-python", "msgs": ["what SQLAlchemy models are defined in the stocky project"]},
    {"id": 474, "tag": "code-python", "msgs": ["how does stocky use pgvector for embedding-based similarity"]},
    {"id": 475, "tag": "code-python", "msgs": ["review stocky's pyproject.toml — what are the main dependencies"]},
    {"id": 476, "tag": "code-python", "msgs": ["how does stocky's train pipeline prepare data for scikit-learn"]},
    {"id": 477, "tag": "code-python", "msgs": ["what is the overall architecture of the stocky trading system"]},
    {"id": 478, "tag": "code-python", "msgs": ["how does stocky handle missing data in the feature engineering step"]},
    {"id": 479, "tag": "code-python", "msgs": ["explain how stocky's pipeline stages connect: ingest, features, labels, train, simulate"]},
    {"id": 480, "tag": "code-python", "msgs": ["what validation does stocky perform on incoming stock data"]},
    {"id": 481, "tag": "code-python", "msgs": ["how does the otomus Python ML hub handle inference requests"]},
    {"id": 482, "tag": "code-python", "msgs": ["what protobuf definitions does otomus use for service communication"]},
    {"id": 483, "tag": "code-python", "msgs": ["how does otomus handle multi-language support across Go, Python, and Dart"]},
    {"id": 484, "tag": "code-python", "msgs": ["explain the service discovery mechanism in otomus using mDNS"]},
    {"id": 485, "tag": "code-python", "msgs": ["what Docker Compose services does otomus define"]},
    {"id": 486, "tag": "code-python", "msgs": ["how does otomus's identity service work in Go"]},
    {"id": 487, "tag": "code-python", "msgs": ["review the otomus discovery service — how does it register services"]},
    {"id": 488, "tag": "code-python", "msgs": ["what is the communication flow between otomus Go services and the Python ML hub"]},
    {"id": 489, "tag": "code-python", "msgs": ["how does otomus's inference service route requests to different models"]},
    {"id": 490, "tag": "code-python", "msgs": ["explain how otomus uses Go 1.22 features in its services"]},
    {"id": 491, "tag": "code-python", "msgs": ["explain Python decorators with an example"]},
    {"id": 492, "tag": "code-python", "msgs": ["what is the difference between a list and a tuple in Python"]},
    {"id": 493, "tag": "code-python", "msgs": ["explain Python generators and when to use them"]},
    {"id": 494, "tag": "code-python", "msgs": ["how does Python's GIL affect multithreading"]},
    {"id": 495, "tag": "code-python", "msgs": ["explain the difference between deepcopy and shallow copy in Python"]},
    {"id": 496, "tag": "code-python", "msgs": ["how do async/await work in Python"]},
    {"id": 497, "tag": "code-python", "msgs": ["explain Python's dataclasses and when to use them"]},
    {"id": 498, "tag": "code-python", "msgs": ["what is the difference between @staticmethod and @classmethod"]},
    {"id": 499, "tag": "code-python", "msgs": ["explain Python's context managers and the with statement"]},
    {"id": 500, "tag": "code-python", "msgs": ["how does Python's type hint system work"]},
    {"id": 501, "tag": "code-python", "msgs": ["explain Python metaclasses with a simple example"]},
    {"id": 502, "tag": "code-python", "msgs": ["what are Python descriptors and how do they work"]},
    {"id": 503, "tag": "code-python", "msgs": ["explain Python's walrus operator :="]},
    {"id": 504, "tag": "code-python", "msgs": ["how does Python's match statement work (3.10+)"]},
    {"id": 505, "tag": "code-python", "msgs": ["explain list comprehensions vs generator expressions in Python"]},
    {"id": 506, "tag": "code-python", "msgs": ["how do I use Python's functools.lru_cache"]},
    {"id": 507, "tag": "code-python", "msgs": ["explain Python's ABC (abstract base class) module"]},
    {"id": 508, "tag": "code-python", "msgs": ["what is the difference between threading and multiprocessing in Python"]},
    {"id": 509, "tag": "code-python", "msgs": ["explain how Python's property decorator works"]},
    {"id": 510, "tag": "code-python", "msgs": ["how does Python's collections.defaultdict work"]},
    {"id": 511, "tag": "code-python", "msgs": ["in the stocky project, how are feature columns named and organized"]},
    {"id": 512, "tag": "code-python", "msgs": ["what error handling patterns does stocky use in its pipeline"]},
    {"id": 513, "tag": "code-python", "msgs": ["how does stocky store and retrieve trained model artifacts"]},
    {"id": 514, "tag": "code-python", "msgs": ["review stocky's data flow from raw prices to predictions"]},
    {"id": 515, "tag": "code-python", "msgs": ["how does stocky handle rate limiting when fetching from yfinance"]},
    {"id": 516, "tag": "code-python", "msgs": ["what configuration options does stocky expose via its CLI"]},
    {"id": 517, "tag": "code-python", "msgs": ["how does stocky use pandas for data manipulation in the pipeline"]},
    {"id": 518, "tag": "code-python", "msgs": ["explain how stocky's simulation module calculates returns"]},
    {"id": 519, "tag": "code-python", "msgs": ["what test structure does the stocky project use"]},
    {"id": 520, "tag": "code-python", "msgs": ["how does stocky handle database connection pooling with SQLAlchemy"]},
    {"id": 521, "tag": "code-python", "msgs": ["explain Python's itertools module and common patterns"]},
    {"id": 522, "tag": "code-python", "msgs": ["how do I use pytest fixtures effectively"]},
    {"id": 523, "tag": "code-python", "msgs": ["explain Python's __init__ vs __new__ methods"]},
    {"id": 524, "tag": "code-python", "msgs": ["how does Python's logging module work"]},
    {"id": 525, "tag": "code-python", "msgs": ["explain Python's dunder methods and operator overloading"]},
    {"id": 526, "tag": "code-python", "msgs": ["how do I use Python's pathlib module for file operations"]},
    {"id": 527, "tag": "code-python", "msgs": ["explain Python's slots and memory optimization"]},
    {"id": 528, "tag": "code-python", "msgs": ["how does Python's concurrent.futures work"]},
    {"id": 529, "tag": "code-python", "msgs": ["explain Python's contextlib module"]},
    {"id": 530, "tag": "code-python", "msgs": ["how do I handle circular imports in Python"]},
    {"id": 531, "tag": "code-python", "msgs": ["how does otomus's Flutter shell communicate with backend services"]},
    {"id": 532, "tag": "code-python", "msgs": ["what API endpoints does the otomus inference service expose"]},
    {"id": 533, "tag": "code-python", "msgs": ["explain the otomus project directory structure"]},
    {"id": 534, "tag": "code-python", "msgs": ["how does otomus handle authentication in the identity service"]},
    {"id": 535, "tag": "code-python", "msgs": ["what build system does otomus use for the Go services"]},
    {"id": 536, "tag": "code-python", "msgs": ["review the otomus Docker Compose networking setup"]},
    {"id": 537, "tag": "code-python", "msgs": ["how does otomus handle model versioning in the ML hub"]},
    {"id": 538, "tag": "code-python", "msgs": ["what monitoring or health check mechanisms does otomus implement"]},
    {"id": 539, "tag": "code-python", "msgs": ["explain how otomus protobuf schemas are shared across languages"]},
    {"id": 540, "tag": "code-python", "msgs": ["how does otomus handle graceful shutdown of Go services"]},
    {"id": 541, "tag": "code-python", "msgs": ["in stocky, how are the Alembic migration versions organized"]},
    {"id": 542, "tag": "code-python", "msgs": ["what approach does stocky take for feature selection before training"]},
    {"id": 543, "tag": "code-python", "msgs": ["how does stocky handle stock splits and dividends in its data"]},
    {"id": 544, "tag": "code-python", "msgs": ["review stocky's Poetry lock file — are there any outdated dependencies"]},
    {"id": 545, "tag": "code-python", "msgs": ["what is stocky's approach to cross-validation during model training"]},
    {"id": 546, "tag": "code-python", "msgs": ["how does stocky's simulate command generate trade signals"]},
    {"id": 547, "tag": "code-python", "msgs": ["explain how stocky normalizes feature data before training"]},
    {"id": 548, "tag": "code-python", "msgs": ["what logging does stocky implement across pipeline stages"]},
    {"id": 549, "tag": "code-python", "msgs": ["how does stocky define and manage database sessions"]},
    {"id": 550, "tag": "code-python", "msgs": ["review the stocky ingest module's retry logic for API failures"]},
    {"id": 551, "tag": "code-python", "msgs": ["explain Python's weakref module and when to use it"]},
    {"id": 552, "tag": "code-python", "msgs": ["how do I use Python's re module for regex patterns"]},
    {"id": 553, "tag": "code-python", "msgs": ["explain Python's importlib and dynamic imports"]},
    {"id": 554, "tag": "code-python", "msgs": ["how do I use Python's struct module for binary data"]},
    {"id": 555, "tag": "code-python", "msgs": ["explain Python's enum module"]},
    {"id": 556, "tag": "code-python", "msgs": ["how do I use Python's argparse module"]},
    {"id": 557, "tag": "code-python", "msgs": ["explain Python's unittest module and test patterns"]},
    {"id": 558, "tag": "code-python", "msgs": ["how does Python garbage collection work"]},
    {"id": 559, "tag": "code-python", "msgs": ["explain Python's asyncio event loop"]},
    {"id": 560, "tag": "code-python", "msgs": ["how do I profile Python code for performance bottlenecks"]},

    # ═══════════════════════════════════════════════════════════════════════
    # CODE-JS — Project analysis & JS/TS questions (561-660)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 561, "tag": "code-js", "msgs": ["in the nanan-ai project, how is the Nx monorepo structured"]},
    {"id": 562, "tag": "code-js", "msgs": ["explain how nanan-ai's NestJS backend handles song detection"]},
    {"id": 563, "tag": "code-js", "msgs": ["what Prisma models does nanan-ai define for the song game"]},
    {"id": 564, "tag": "code-js", "msgs": ["how does nanan-ai's Next.js 14 frontend handle routing"]},
    {"id": 565, "tag": "code-js", "msgs": ["review the nanan-ai apps/public-web structure — what pages exist"]},
    {"id": 566, "tag": "code-js", "msgs": ["how does nanan-ai use React Query for data fetching"]},
    {"id": 567, "tag": "code-js", "msgs": ["what API endpoints does nanan-ai's public-server expose"]},
    {"id": 568, "tag": "code-js", "msgs": ["explain the relationship between nanan-ai's apps and libs directories"]},
    {"id": 569, "tag": "code-js", "msgs": ["how does nanan-ai's bo-client (back office) differ from public-web"]},
    {"id": 570, "tag": "code-js", "msgs": ["what TypeScript types does nanan-ai share across apps via libs"]},
    {"id": 571, "tag": "code-js", "msgs": ["review nanan-ai's Prisma schema — what tables and relations exist"]},
    {"id": 572, "tag": "code-js", "msgs": ["how does nanan-ai handle real-time game state updates"]},
    {"id": 573, "tag": "code-js", "msgs": ["what Nx build targets does nanan-ai configure"]},
    {"id": 574, "tag": "code-js", "msgs": ["explain nanan-ai's authentication flow between frontend and backend"]},
    {"id": 575, "tag": "code-js", "msgs": ["how does nanan-ai's PostgreSQL database integrate with Prisma"]},
    {"id": 576, "tag": "code-js", "msgs": ["what NestJS modules and providers does nanan-ai define"]},
    {"id": 577, "tag": "code-js", "msgs": ["review nanan-ai's package.json — what scripts are available"]},
    {"id": 578, "tag": "code-js", "msgs": ["how does nanan-ai handle error boundaries in the Next.js frontend"]},
    {"id": 579, "tag": "code-js", "msgs": ["what environment variables does nanan-ai require"]},
    {"id": 580, "tag": "code-js", "msgs": ["explain nanan-ai's song matching algorithm"]},
    {"id": 581, "tag": "code-js", "msgs": ["in the my-bot project, how does the state machine work (PLANNING, EXECUTING, IDLE)"]},
    {"id": 582, "tag": "code-js", "msgs": ["how does my-bot use Baileys for WhatsApp integration"]},
    {"id": 583, "tag": "code-js", "msgs": ["explain my-bot's better-sqlite3 database schema"]},
    {"id": 584, "tag": "code-js", "msgs": ["how does my-bot handle the transition from PLANNING to EXECUTING state"]},
    {"id": 585, "tag": "code-js", "msgs": ["review my-bot's Express routes — what endpoints exist"]},
    {"id": 586, "tag": "code-js", "msgs": ["how does my-bot use PM2 for process management"]},
    {"id": 587, "tag": "code-js", "msgs": ["explain my-bot's Cloudflare Tunnel configuration"]},
    {"id": 588, "tag": "code-js", "msgs": ["how does my-bot use puppeteer for web automation"]},
    {"id": 589, "tag": "code-js", "msgs": ["review my-bot's simple-git integration — what git operations does it perform"]},
    {"id": 590, "tag": "code-js", "msgs": ["how does my-bot interact with GitHub via octokit"]},
    {"id": 591, "tag": "code-js", "msgs": ["what is my-bot's overall architecture as an autonomous coding agent"]},
    {"id": 592, "tag": "code-js", "msgs": ["how does my-bot handle message queuing from WhatsApp"]},
    {"id": 593, "tag": "code-js", "msgs": ["what error recovery mechanisms does my-bot implement"]},
    {"id": 594, "tag": "code-js", "msgs": ["explain my-bot's task planning logic"]},
    {"id": 595, "tag": "code-js", "msgs": ["how does my-bot store conversation history in SQLite"]},
    {"id": 596, "tag": "code-js", "msgs": ["review my-bot's package.json — what dependencies does it use"]},
    {"id": 597, "tag": "code-js", "msgs": ["how does my-bot handle concurrent task execution"]},
    {"id": 598, "tag": "code-js", "msgs": ["what logging does my-bot implement"]},
    {"id": 599, "tag": "code-js", "msgs": ["explain how my-bot manages file operations during code generation"]},
    {"id": 600, "tag": "code-js", "msgs": ["how does my-bot validate incoming WhatsApp messages"]},
    {"id": 601, "tag": "code-js", "msgs": ["explain JavaScript closures with an example"]},
    {"id": 602, "tag": "code-js", "msgs": ["how does the JavaScript event loop work"]},
    {"id": 603, "tag": "code-js", "msgs": ["explain prototypal inheritance in JavaScript"]},
    {"id": 604, "tag": "code-js", "msgs": ["what is the difference between == and === in JavaScript"]},
    {"id": 605, "tag": "code-js", "msgs": ["explain JavaScript's this keyword in different contexts"]},
    {"id": 606, "tag": "code-js", "msgs": ["how do async/await work in JavaScript"]},
    {"id": 607, "tag": "code-js", "msgs": ["explain JavaScript modules — ESM vs CommonJS"]},
    {"id": 608, "tag": "code-js", "msgs": ["what is the difference between var, let, and const"]},
    {"id": 609, "tag": "code-js", "msgs": ["explain TypeScript conditional types"]},
    {"id": 610, "tag": "code-js", "msgs": ["how does JavaScript's garbage collection work"]},
    {"id": 611, "tag": "code-js", "msgs": ["explain TypeScript's infer keyword"]},
    {"id": 612, "tag": "code-js", "msgs": ["how do JavaScript Promises work under the hood"]},
    {"id": 613, "tag": "code-js", "msgs": ["explain JavaScript's Proxy and Reflect APIs"]},
    {"id": 614, "tag": "code-js", "msgs": ["what are TypeScript discriminated unions"]},
    {"id": 615, "tag": "code-js", "msgs": ["explain JavaScript's WeakMap and WeakSet"]},
    {"id": 616, "tag": "code-js", "msgs": ["how does JavaScript's event delegation work"]},
    {"id": 617, "tag": "code-js", "msgs": ["explain TypeScript template literal types"]},
    {"id": 618, "tag": "code-js", "msgs": ["what is the temporal dead zone in JavaScript"]},
    {"id": 619, "tag": "code-js", "msgs": ["explain JavaScript generator functions"]},
    {"id": 620, "tag": "code-js", "msgs": ["how do JavaScript async iterators work"]},
    {"id": 621, "tag": "code-js", "msgs": ["in the nanan-ai project, how are game rounds managed"]},
    {"id": 622, "tag": "code-js", "msgs": ["what middleware does nanan-ai's NestJS backend use"]},
    {"id": 623, "tag": "code-js", "msgs": ["how does nanan-ai handle database migrations with Prisma"]},
    {"id": 624, "tag": "code-js", "msgs": ["review nanan-ai's frontend component structure"]},
    {"id": 625, "tag": "code-js", "msgs": ["what testing setup does nanan-ai use across the monorepo"]},
    {"id": 626, "tag": "code-js", "msgs": ["how does nanan-ai handle audio playback in the song game"]},
    {"id": 627, "tag": "code-js", "msgs": ["what shared utilities exist in nanan-ai's libs directory"]},
    {"id": 628, "tag": "code-js", "msgs": ["how does nanan-ai's scoring system work for the song game"]},
    {"id": 629, "tag": "code-js", "msgs": ["review nanan-ai's tsconfig setup across the monorepo"]},
    {"id": 630, "tag": "code-js", "msgs": ["how does nanan-ai handle deployment and CI/CD"]},
    {"id": 631, "tag": "code-js", "msgs": ["explain the difference between SSR and CSR in Next.js"]},
    {"id": 632, "tag": "code-js", "msgs": ["how do I use Zod for schema validation in TypeScript"]},
    {"id": 633, "tag": "code-js", "msgs": ["explain Next.js server components vs client components"]},
    {"id": 634, "tag": "code-js", "msgs": ["how does Node.js module resolution work"]},
    {"id": 635, "tag": "code-js", "msgs": ["explain JavaScript's Symbol type and its uses"]},
    {"id": 636, "tag": "code-js", "msgs": ["how do JavaScript Web Workers work"]},
    {"id": 637, "tag": "code-js", "msgs": ["explain JavaScript's Intl API for internationalization"]},
    {"id": 638, "tag": "code-js", "msgs": ["how does JavaScript's AbortController work"]},
    {"id": 639, "tag": "code-js", "msgs": ["explain JavaScript's structuredClone function"]},
    {"id": 640, "tag": "code-js", "msgs": ["how do Node.js streams work"]},
    {"id": 641, "tag": "code-js", "msgs": ["how does my-bot decide when to create a new branch vs commit to existing"]},
    {"id": 642, "tag": "code-js", "msgs": ["what is my-bot's approach to breaking down complex tasks into steps"]},
    {"id": 643, "tag": "code-js", "msgs": ["how does my-bot handle authentication with GitHub via octokit"]},
    {"id": 644, "tag": "code-js", "msgs": ["review my-bot's Baileys session management"]},
    {"id": 645, "tag": "code-js", "msgs": ["what file types can my-bot's puppeteer integration process"]},
    {"id": 646, "tag": "code-js", "msgs": ["how does my-bot handle timeouts and retries"]},
    {"id": 647, "tag": "code-js", "msgs": ["explain my-bot's approach to code review via GitHub"]},
    {"id": 648, "tag": "code-js", "msgs": ["how does my-bot persist state across PM2 restarts"]},
    {"id": 649, "tag": "code-js", "msgs": ["what security measures does my-bot implement for incoming messages"]},
    {"id": 650, "tag": "code-js", "msgs": ["how does my-bot manage environment configuration"]},
    {"id": 651, "tag": "code-js", "msgs": ["how do I use Node.js worker threads"]},
    {"id": 652, "tag": "code-js", "msgs": ["explain JavaScript's SharedArrayBuffer and Atomics"]},
    {"id": 653, "tag": "code-js", "msgs": ["how do JavaScript import maps work"]},
    {"id": 654, "tag": "code-js", "msgs": ["explain JavaScript's tail call optimization"]},
    {"id": 655, "tag": "code-js", "msgs": ["how do I use the Intersection Observer API"]},
    {"id": 656, "tag": "code-js", "msgs": ["explain TypeScript's utility types (Partial, Pick, Omit, etc.)"]},
    {"id": 657, "tag": "code-js", "msgs": ["how does JavaScript's Map differ from a plain object"]},
    {"id": 658, "tag": "code-js", "msgs": ["explain the JavaScript decorator proposal"]},
    {"id": 659, "tag": "code-js", "msgs": ["how do I use the Fetch API with streaming responses"]},
    {"id": 660, "tag": "code-js", "msgs": ["explain JavaScript's FinalizationRegistry"]},

    # ═══════════════════════════════════════════════════════════════════════
    # CODE-SQL — Database and SQL tasks (661-720)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 661, "tag": "code-sql", "msgs": ["write a SQL query to find the top 5 customers by total orders"]},
    {"id": 662, "tag": "code-sql", "msgs": ["explain the difference between INNER JOIN and LEFT JOIN"]},
    {"id": 663, "tag": "code-sql", "msgs": ["write a SQL query to find duplicate rows in a table"]},
    {"id": 664, "tag": "code-sql", "msgs": ["how do I create an index in PostgreSQL"]},
    {"id": 665, "tag": "code-sql", "msgs": ["write a SQL query with a window function for running totals"]},
    {"id": 666, "tag": "code-sql", "msgs": ["explain database normalization (1NF, 2NF, 3NF)"]},
    {"id": 667, "tag": "code-sql", "msgs": ["write a SQL migration to add a column with default value"]},
    {"id": 668, "tag": "code-sql", "msgs": ["how do I optimize a slow SQL query"]},
    {"id": 669, "tag": "code-sql", "msgs": ["write a SQL query for pagination with offset"]},
    {"id": 670, "tag": "code-sql", "msgs": ["explain ACID properties in databases"]},
    {"id": 671, "tag": "code-sql", "msgs": ["write a SQL query to pivot rows to columns"]},
    {"id": 672, "tag": "code-sql", "msgs": ["how do I set up connection pooling for PostgreSQL"]},
    {"id": 673, "tag": "code-sql", "msgs": ["write a SQL query to find the second highest salary"]},
    {"id": 674, "tag": "code-sql", "msgs": ["explain database sharding"]},
    {"id": 675, "tag": "code-sql", "msgs": ["write a SQL query with a recursive CTE"]},
    {"id": 676, "tag": "code-sql", "msgs": ["how do I create a stored procedure"]},
    {"id": 677, "tag": "code-sql", "msgs": ["write a SQL query to calculate moving average"]},
    {"id": 678, "tag": "code-sql", "msgs": ["explain the difference between WHERE and HAVING"]},
    {"id": 679, "tag": "code-sql", "msgs": ["write a SQL query to merge/upsert data"]},
    {"id": 680, "tag": "code-sql", "msgs": ["how do I use SQLite with Python for a simple app"]},
    {"id": 681, "tag": "code-sql", "msgs": ["write a SQL query to find gaps in sequential IDs"]},
    {"id": 682, "tag": "code-sql", "msgs": ["explain database replication strategies"]},
    {"id": 683, "tag": "code-sql", "msgs": ["write a SQL query for full-text search"]},
    {"id": 684, "tag": "code-sql", "msgs": ["how do I design a schema for a trading system"]},
    {"id": 685, "tag": "code-sql", "msgs": ["write a SQL query to calculate retention rate"]},
    {"id": 686, "tag": "code-sql", "msgs": ["explain the difference between clustered and non-clustered indexes"]},
    {"id": 687, "tag": "code-sql", "msgs": ["write a SQL query to transpose columns to rows"]},
    {"id": 688, "tag": "code-sql", "msgs": ["how do I backup and restore a PostgreSQL database"]},
    {"id": 689, "tag": "code-sql", "msgs": ["write a SQL query for time-series aggregation by hour"]},
    {"id": 690, "tag": "code-sql", "msgs": ["explain optimistic vs pessimistic locking"]},
    {"id": 691, "tag": "code-sql", "msgs": ["write a Prisma schema for a blog application"]},
    {"id": 692, "tag": "code-sql", "msgs": ["how do I use TimescaleDB for time-series data"]},
    {"id": 693, "tag": "code-sql", "msgs": ["write a SQL query to find users who logged in every day this week"]},
    {"id": 694, "tag": "code-sql", "msgs": ["explain database connection pooling"]},
    {"id": 695, "tag": "code-sql", "msgs": ["write a SQL query to calculate percentiles"]},
    {"id": 696, "tag": "code-sql", "msgs": ["how do I model a many-to-many relationship"]},
    {"id": 697, "tag": "code-sql", "msgs": ["write a SQL trigger for audit logging"]},
    {"id": 698, "tag": "code-sql", "msgs": ["explain the difference between Redis and PostgreSQL"]},
    {"id": 699, "tag": "code-sql", "msgs": ["write a SQL query to find the longest streak of consecutive dates"]},
    {"id": 700, "tag": "code-sql", "msgs": ["how do I design a schema for a song detection game"]},
    {"id": 701, "tag": "code-sql", "msgs": ["write a SQL query for hierarchical data using ltree"]},
    {"id": 702, "tag": "code-sql", "msgs": ["explain database partitioning strategies"]},
    {"id": 703, "tag": "code-sql", "msgs": ["write a SQL query to find overlapping date ranges"]},
    {"id": 704, "tag": "code-sql", "msgs": ["how do I migrate from SQLite to PostgreSQL"]},
    {"id": 705, "tag": "code-sql", "msgs": ["write a SQL query for a leaderboard with rank"]},
    {"id": 706, "tag": "code-sql", "msgs": ["explain database vacuum and autovacuum"]},
    {"id": 707, "tag": "code-sql", "msgs": ["write a SQL query to calculate cohort analysis"]},
    {"id": 708, "tag": "code-sql", "msgs": ["how do I implement soft deletes in SQL"]},
    {"id": 709, "tag": "code-sql", "msgs": ["write a SQL query for a recommendation system"]},
    {"id": 710, "tag": "code-sql", "msgs": ["explain the WAL (Write-Ahead Logging)"]},
    {"id": 711, "tag": "code-sql", "msgs": ["write a Knex.js migration for creating tables"]},
    {"id": 712, "tag": "code-sql", "msgs": ["how do I use JSON columns in PostgreSQL"]},
    {"id": 713, "tag": "code-sql", "msgs": ["write a SQL query to detect anomalies in time-series data"]},
    {"id": 714, "tag": "code-sql", "msgs": ["explain database connection strings"]},
    {"id": 715, "tag": "code-sql", "msgs": ["write a SQL query for event sourcing pattern"]},
    {"id": 716, "tag": "code-sql", "msgs": ["how do I use EXPLAIN ANALYZE to debug queries"]},
    {"id": 717, "tag": "code-sql", "msgs": ["write a SQL function to generate a UUID"]},
    {"id": 718, "tag": "code-sql", "msgs": ["explain the CAP theorem with examples"]},
    {"id": 719, "tag": "code-sql", "msgs": ["write a SQL query to find the most active users by month"]},
    {"id": 720, "tag": "code-sql", "msgs": ["how do I set up read replicas in PostgreSQL"]},

    # ═══════════════════════════════════════════════════════════════════════
    # CODE-WEB — HTML/CSS/React/Web dev (721-780)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 721, "tag": "code-web", "msgs": ["write HTML for a responsive navigation bar"]},
    {"id": 722, "tag": "code-web", "msgs": ["write CSS for a card component with shadow"]},
    {"id": 723, "tag": "code-web", "msgs": ["create a React component for a toggle switch"]},
    {"id": 724, "tag": "code-web", "msgs": ["how do I center a div vertically and horizontally"]},
    {"id": 725, "tag": "code-web", "msgs": ["write CSS for a grid layout with 3 columns"]},
    {"id": 726, "tag": "code-web", "msgs": ["create a React form with validation"]},
    {"id": 727, "tag": "code-web", "msgs": ["how do I make a website responsive"]},
    {"id": 728, "tag": "code-web", "msgs": ["write HTML/CSS for a hero section"]},
    {"id": 729, "tag": "code-web", "msgs": ["create a React component for a dropdown menu"]},
    {"id": 730, "tag": "code-web", "msgs": ["how do I use CSS flexbox"]},
    {"id": 731, "tag": "code-web", "msgs": ["write HTML for an accessible form"]},
    {"id": 732, "tag": "code-web", "msgs": ["create a React component for a toast notification"]},
    {"id": 733, "tag": "code-web", "msgs": ["how do I implement dark mode with CSS variables"]},
    {"id": 734, "tag": "code-web", "msgs": ["write CSS animations for a loading spinner"]},
    {"id": 735, "tag": "code-web", "msgs": ["create a React context for theme management"]},
    {"id": 736, "tag": "code-web", "msgs": ["how do I optimize images for the web"]},
    {"id": 737, "tag": "code-web", "msgs": ["write HTML/CSS for a pricing table"]},
    {"id": 738, "tag": "code-web", "msgs": ["create a React component for a search bar with autocomplete"]},
    {"id": 739, "tag": "code-web", "msgs": ["how do I implement lazy loading for images"]},
    {"id": 740, "tag": "code-web", "msgs": ["write CSS for a sticky header"]},
    {"id": 741, "tag": "code-web", "msgs": ["create a React hook for window resize detection"]},
    {"id": 742, "tag": "code-web", "msgs": ["how do I set up Tailwind CSS"]},
    {"id": 743, "tag": "code-web", "msgs": ["write HTML for a semantic blog post layout"]},
    {"id": 744, "tag": "code-web", "msgs": ["create a React component for file upload with drag and drop"]},
    {"id": 745, "tag": "code-web", "msgs": ["how do I implement CSS-only tooltips"]},
    {"id": 746, "tag": "code-web", "msgs": ["write a React component for a pagination control"]},
    {"id": 747, "tag": "code-web", "msgs": ["how do I use CSS container queries"]},
    {"id": 748, "tag": "code-web", "msgs": ["create a React component for a carousel/slider"]},
    {"id": 749, "tag": "code-web", "msgs": ["write CSS for a glassmorphism effect"]},
    {"id": 750, "tag": "code-web", "msgs": ["how do I implement skeleton loading screens"]},
    {"id": 751, "tag": "code-web", "msgs": ["create a Next.js page with SSR data fetching"]},
    {"id": 752, "tag": "code-web", "msgs": ["write CSS for a responsive footer"]},
    {"id": 753, "tag": "code-web", "msgs": ["create a React component for a stepper/wizard form"]},
    {"id": 754, "tag": "code-web", "msgs": ["how do I use CSS Grid for complex layouts"]},
    {"id": 755, "tag": "code-web", "msgs": ["write HTML/CSS for an email template"]},
    {"id": 756, "tag": "code-web", "msgs": ["create a React error boundary component"]},
    {"id": 757, "tag": "code-web", "msgs": ["how do I implement smooth scrolling"]},
    {"id": 758, "tag": "code-web", "msgs": ["write a React component for a countdown timer"]},
    {"id": 759, "tag": "code-web", "msgs": ["how do I make a PWA (progressive web app)"]},
    {"id": 760, "tag": "code-web", "msgs": ["create a React component for syntax highlighting"]},
    {"id": 761, "tag": "code-web", "msgs": ["write CSS for a masonry layout"]},
    {"id": 762, "tag": "code-web", "msgs": ["how do I implement web accessibility (WCAG)"]},
    {"id": 763, "tag": "code-web", "msgs": ["create a React component for a color picker"]},
    {"id": 764, "tag": "code-web", "msgs": ["write HTML/CSS for a login page"]},
    {"id": 765, "tag": "code-web", "msgs": ["how do I use CSS aspect-ratio property"]},
    {"id": 766, "tag": "code-web", "msgs": ["create a React component for a rich text editor"]},
    {"id": 767, "tag": "code-web", "msgs": ["write CSS for a responsive sidebar layout"]},
    {"id": 768, "tag": "code-web", "msgs": ["how do I implement meta tags for SEO"]},
    {"id": 769, "tag": "code-web", "msgs": ["create a React component for a chart (bar chart)"]},
    {"id": 770, "tag": "code-web", "msgs": ["write CSS for a timeline component"]},
    {"id": 771, "tag": "code-web", "msgs": ["how do I handle forms in Next.js server actions"]},
    {"id": 772, "tag": "code-web", "msgs": ["create a React component for an image gallery"]},
    {"id": 773, "tag": "code-web", "msgs": ["write CSS for a gradient text effect"]},
    {"id": 774, "tag": "code-web", "msgs": ["how do I use CSS scroll-snap"]},
    {"id": 775, "tag": "code-web", "msgs": ["create a React component for breadcrumbs"]},
    {"id": 776, "tag": "code-web", "msgs": ["write HTML for a responsive email layout"]},
    {"id": 777, "tag": "code-web", "msgs": ["how do I implement infinite scroll in React"]},
    {"id": 778, "tag": "code-web", "msgs": ["create a React component for a notification badge"]},
    {"id": 779, "tag": "code-web", "msgs": ["write CSS for a neumorphism button"]},
    {"id": 780, "tag": "code-web", "msgs": ["how do I optimize Core Web Vitals"]},

    # ═══════════════════════════════════════════════════════════════════════
    # CODE-API — API design and integration (781-830)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 781, "tag": "code-api", "msgs": ["design a REST API for a todo app"]},
    {"id": 782, "tag": "code-api", "msgs": ["what are the best practices for API versioning"]},
    {"id": 783, "tag": "code-api", "msgs": ["write a FastAPI endpoint for user registration"]},
    {"id": 784, "tag": "code-api", "msgs": ["explain REST vs GraphQL vs gRPC"]},
    {"id": 785, "tag": "code-api", "msgs": ["how do I implement API rate limiting"]},
    {"id": 786, "tag": "code-api", "msgs": ["write an OpenAPI spec for a user endpoint"]},
    {"id": 787, "tag": "code-api", "msgs": ["how do I implement OAuth2 flow"]},
    {"id": 788, "tag": "code-api", "msgs": ["design a webhook system"]},
    {"id": 789, "tag": "code-api", "msgs": ["write a GraphQL schema for a blog"]},
    {"id": 790, "tag": "code-api", "msgs": ["how do I handle API pagination"]},
    {"id": 791, "tag": "code-api", "msgs": ["design an API for a chat application"]},
    {"id": 792, "tag": "code-api", "msgs": ["how do I implement API key authentication"]},
    {"id": 793, "tag": "code-api", "msgs": ["write a middleware for request logging"]},
    {"id": 794, "tag": "code-api", "msgs": ["explain HATEOAS in REST APIs"]},
    {"id": 795, "tag": "code-api", "msgs": ["how do I design idempotent APIs"]},
    {"id": 796, "tag": "code-api", "msgs": ["write a health check API endpoint"]},
    {"id": 797, "tag": "code-api", "msgs": ["how do I implement API caching with Redis"]},
    {"id": 798, "tag": "code-api", "msgs": ["design an API for a trading platform"]},
    {"id": 799, "tag": "code-api", "msgs": ["how do I handle file uploads via API"]},
    {"id": 800, "tag": "code-api", "msgs": ["write an API client with retry logic"]},
    {"id": 801, "tag": "code-api", "msgs": ["how do I implement server-sent events"]},
    {"id": 802, "tag": "code-api", "msgs": ["design a notification API"]},
    {"id": 803, "tag": "code-api", "msgs": ["how do I secure a public API"]},
    {"id": 804, "tag": "code-api", "msgs": ["write API error handling best practices"]},
    {"id": 805, "tag": "code-api", "msgs": ["how do I implement API gateway pattern"]},
    {"id": 806, "tag": "code-api", "msgs": ["design a search API with filters and sorting"]},
    {"id": 807, "tag": "code-api", "msgs": ["how do I use Protocol Buffers for API communication"]},
    {"id": 808, "tag": "code-api", "msgs": ["write a swagger doc for a CRUD API"]},
    {"id": 809, "tag": "code-api", "msgs": ["how do I implement long polling"]},
    {"id": 810, "tag": "code-api", "msgs": ["design a multi-tenant API"]},
    {"id": 811, "tag": "code-api", "msgs": ["how do I implement content negotiation"]},
    {"id": 812, "tag": "code-api", "msgs": ["write an API for real-time stock prices"]},
    {"id": 813, "tag": "code-api", "msgs": ["how do I implement API versioning with URL paths"]},
    {"id": 814, "tag": "code-api", "msgs": ["design an API for a music streaming service"]},
    {"id": 815, "tag": "code-api", "msgs": ["how do I handle API deprecation"]},
    {"id": 816, "tag": "code-api", "msgs": ["write a proxy API to aggregate multiple services"]},
    {"id": 817, "tag": "code-api", "msgs": ["how do I implement API request validation"]},
    {"id": 818, "tag": "code-api", "msgs": ["design a payment processing API"]},
    {"id": 819, "tag": "code-api", "msgs": ["how do I implement batch API operations"]},
    {"id": 820, "tag": "code-api", "msgs": ["write an API for geolocation services"]},
    {"id": 821, "tag": "code-api", "msgs": ["how do I document APIs with Redoc"]},
    {"id": 822, "tag": "code-api", "msgs": ["design an API for a calendar service"]},
    {"id": 823, "tag": "code-api", "msgs": ["how do I implement API mocking for development"]},
    {"id": 824, "tag": "code-api", "msgs": ["write integration tests for a REST API"]},
    {"id": 825, "tag": "code-api", "msgs": ["how do I implement CORS correctly"]},
    {"id": 826, "tag": "code-api", "msgs": ["design an API for a CI/CD pipeline"]},
    {"id": 827, "tag": "code-api", "msgs": ["how do I implement API throttling per user"]},
    {"id": 828, "tag": "code-api", "msgs": ["write a webhook receiver endpoint"]},
    {"id": 829, "tag": "code-api", "msgs": ["how do I implement API analytics"]},
    {"id": 830, "tag": "code-api", "msgs": ["design an API for an IoT device management system"]},

    # ═══════════════════════════════════════════════════════════════════════
    # CODE-GIT — Git and version control (831-870)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 831, "tag": "code-git", "msgs": ["how do I undo the last git commit"]},
    {"id": 832, "tag": "code-git", "msgs": ["explain git rebase vs merge"]},
    {"id": 833, "tag": "code-git", "msgs": ["how do I resolve a merge conflict"]},
    {"id": 834, "tag": "code-git", "msgs": ["how do I squash commits"]},
    {"id": 835, "tag": "code-git", "msgs": ["write a .gitignore for a Python project"]},
    {"id": 836, "tag": "code-git", "msgs": ["how do I cherry-pick a commit"]},
    {"id": 837, "tag": "code-git", "msgs": ["explain git stash and how to use it"]},
    {"id": 838, "tag": "code-git", "msgs": ["how do I set up git hooks"]},
    {"id": 839, "tag": "code-git", "msgs": ["write a git workflow for a team of 5"]},
    {"id": 840, "tag": "code-git", "msgs": ["how do I revert a pushed commit"]},
    {"id": 841, "tag": "code-git", "msgs": ["explain git bisect"]},
    {"id": 842, "tag": "code-git", "msgs": ["how do I create a git tag for a release"]},
    {"id": 843, "tag": "code-git", "msgs": ["write a .gitignore for a Node.js project"]},
    {"id": 844, "tag": "code-git", "msgs": ["how do I set up GitHub Actions for CI"]},
    {"id": 845, "tag": "code-git", "msgs": ["explain git submodules"]},
    {"id": 846, "tag": "code-git", "msgs": ["how do I recover a deleted branch"]},
    {"id": 847, "tag": "code-git", "msgs": ["write a pre-commit hook for linting"]},
    {"id": 848, "tag": "code-git", "msgs": ["how do I clean up old branches"]},
    {"id": 849, "tag": "code-git", "msgs": ["explain git worktrees"]},
    {"id": 850, "tag": "code-git", "msgs": ["how do I configure git for multiple accounts"]},
    {"id": 851, "tag": "code-git", "msgs": ["write a GitHub Actions workflow for testing"]},
    {"id": 852, "tag": "code-git", "msgs": ["how do I use git blame"]},
    {"id": 853, "tag": "code-git", "msgs": ["explain git reflog"]},
    {"id": 854, "tag": "code-git", "msgs": ["how do I create a PR template"]},
    {"id": 855, "tag": "code-git", "msgs": ["write a conventional commits guide"]},
    {"id": 856, "tag": "code-git", "msgs": ["how do I use git sparse-checkout"]},
    {"id": 857, "tag": "code-git", "msgs": ["explain git flow branching strategy"]},
    {"id": 858, "tag": "code-git", "msgs": ["how do I sign commits with GPG"]},
    {"id": 859, "tag": "code-git", "msgs": ["write a release automation script with git"]},
    {"id": 860, "tag": "code-git", "msgs": ["how do I use git diff to compare branches"]},
    {"id": 861, "tag": "code-git", "msgs": ["explain trunk-based development"]},
    {"id": 862, "tag": "code-git", "msgs": ["how do I set up branch protection rules"]},
    {"id": 863, "tag": "code-git", "msgs": ["write a git commit message template"]},
    {"id": 864, "tag": "code-git", "msgs": ["how do I use git filter-branch to remove a file from history"]},
    {"id": 865, "tag": "code-git", "msgs": ["explain git rerere"]},
    {"id": 866, "tag": "code-git", "msgs": ["how do I migrate from SVN to git"]},
    {"id": 867, "tag": "code-git", "msgs": ["write a GitHub Actions workflow for deployment"]},
    {"id": 868, "tag": "code-git", "msgs": ["how do I use git patches"]},
    {"id": 869, "tag": "code-git", "msgs": ["explain the difference between fetch and pull"]},
    {"id": 870, "tag": "code-git", "msgs": ["how do I set up a git monorepo"]},

    # ═══════════════════════════════════════════════════════════════════════
    # CODE-DEVOPS — Docker, CI/CD, infrastructure (871-920)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 871, "tag": "code-devops", "msgs": ["write a Dockerfile for a Python FastAPI app"]},
    {"id": 872, "tag": "code-devops", "msgs": ["write a docker-compose.yml for a web app with PostgreSQL and Redis"]},
    {"id": 873, "tag": "code-devops", "msgs": ["how do I optimize a Docker image size"]},
    {"id": 874, "tag": "code-devops", "msgs": ["explain Kubernetes pods, services, and deployments"]},
    {"id": 875, "tag": "code-devops", "msgs": ["write a CI/CD pipeline for a Node.js project"]},
    {"id": 876, "tag": "code-devops", "msgs": ["how do I set up nginx as a reverse proxy"]},
    {"id": 877, "tag": "code-devops", "msgs": ["write a bash script to deploy a service"]},
    {"id": 878, "tag": "code-devops", "msgs": ["explain blue-green deployment"]},
    {"id": 879, "tag": "code-devops", "msgs": ["how do I set up SSL/TLS certificates"]},
    {"id": 880, "tag": "code-devops", "msgs": ["write a Kubernetes deployment manifest"]},
    {"id": 881, "tag": "code-devops", "msgs": ["how do I monitor Docker containers"]},
    {"id": 882, "tag": "code-devops", "msgs": ["explain infrastructure as code"]},
    {"id": 883, "tag": "code-devops", "msgs": ["write a Terraform config for an AWS EC2 instance"]},
    {"id": 884, "tag": "code-devops", "msgs": ["how do I set up log aggregation with ELK stack"]},
    {"id": 885, "tag": "code-devops", "msgs": ["write a Docker multi-stage build"]},
    {"id": 886, "tag": "code-devops", "msgs": ["explain canary deployments"]},
    {"id": 887, "tag": "code-devops", "msgs": ["how do I use Docker volumes for data persistence"]},
    {"id": 888, "tag": "code-devops", "msgs": ["write a systemd service file"]},
    {"id": 889, "tag": "code-devops", "msgs": ["how do I set up Prometheus and Grafana"]},
    {"id": 890, "tag": "code-devops", "msgs": ["explain the 12-factor app methodology"]},
    {"id": 891, "tag": "code-devops", "msgs": ["write a Docker healthcheck"]},
    {"id": 892, "tag": "code-devops", "msgs": ["how do I implement rolling updates in Kubernetes"]},
    {"id": 893, "tag": "code-devops", "msgs": ["write a Makefile for a Go project"]},
    {"id": 894, "tag": "code-devops", "msgs": ["how do I set up auto-scaling"]},
    {"id": 895, "tag": "code-devops", "msgs": ["explain service mesh and Istio"]},
    {"id": 896, "tag": "code-devops", "msgs": ["write a cron job for database backups"]},
    {"id": 897, "tag": "code-devops", "msgs": ["how do I configure environment variables securely"]},
    {"id": 898, "tag": "code-devops", "msgs": ["write an Ansible playbook for server setup"]},
    {"id": 899, "tag": "code-devops", "msgs": ["how do I implement zero-downtime deployment"]},
    {"id": 900, "tag": "code-devops", "msgs": ["explain container orchestration"]},
    {"id": 901, "tag": "code-devops", "msgs": ["write a GitHub Actions workflow for Docker build and push"]},
    {"id": 902, "tag": "code-devops", "msgs": ["how do I set up a load balancer"]},
    {"id": 903, "tag": "code-devops", "msgs": ["write a script to rotate log files"]},
    {"id": 904, "tag": "code-devops", "msgs": ["how do I use Docker secrets"]},
    {"id": 905, "tag": "code-devops", "msgs": ["explain GitOps workflow"]},
    {"id": 906, "tag": "code-devops", "msgs": ["write a Kubernetes ConfigMap"]},
    {"id": 907, "tag": "code-devops", "msgs": ["how do I implement circuit breaker pattern in microservices"]},
    {"id": 908, "tag": "code-devops", "msgs": ["write a Docker network configuration"]},
    {"id": 909, "tag": "code-devops", "msgs": ["how do I set up a staging environment"]},
    {"id": 910, "tag": "code-devops", "msgs": ["explain serverless architecture"]},
    {"id": 911, "tag": "code-devops", "msgs": ["write a Dockerfile for a Go microservice"]},
    {"id": 912, "tag": "code-devops", "msgs": ["how do I implement feature flags"]},
    {"id": 913, "tag": "code-devops", "msgs": ["write a Kubernetes ingress configuration"]},
    {"id": 914, "tag": "code-devops", "msgs": ["how do I set up database migrations in CI"]},
    {"id": 915, "tag": "code-devops", "msgs": ["explain chaos engineering"]},
    {"id": 916, "tag": "code-devops", "msgs": ["write a Docker Compose for a development environment"]},
    {"id": 917, "tag": "code-devops", "msgs": ["how do I implement distributed tracing"]},
    {"id": 918, "tag": "code-devops", "msgs": ["write a Kubernetes CronJob manifest"]},
    {"id": 919, "tag": "code-devops", "msgs": ["how do I set up a CDN for a web app"]},
    {"id": 920, "tag": "code-devops", "msgs": ["explain observability: logs, metrics, and traces"]},

    # ═══════════════════════════════════════════════════════════════════════
    # DATA — data processing, CSV, JSON, YAML (921-960)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 921, "tag": "data", "msgs": ["parse this JSON: {\"name\": \"Oron\", \"age\": 30, \"city\": \"Tel Aviv\"}"]},
    {"id": 922, "tag": "data", "msgs": ["convert this CSV to JSON: name,age\\nAlice,30\\nBob,25"]},
    {"id": 923, "tag": "data", "msgs": ["validate this email: oron@example.com"]},
    {"id": 924, "tag": "data", "msgs": ["format this JSON prettily: {\"a\":1,\"b\":{\"c\":2,\"d\":3}}"]},
    {"id": 925, "tag": "data", "msgs": ["convert YAML to JSON: name: test\\nversion: 1.0"]},
    {"id": 926, "tag": "data", "msgs": ["parse this date: March 15, 2024"]},
    {"id": 927, "tag": "data", "msgs": ["generate a UUID"]},
    {"id": 928, "tag": "data", "msgs": ["hash this string with SHA256: hello world"]},
    {"id": 929, "tag": "data", "msgs": ["encode this to base64: Hello, World!"]},
    {"id": 930, "tag": "data", "msgs": ["decode this base64: SGVsbG8gV29ybGQ="]},
    {"id": 931, "tag": "data", "msgs": ["generate a slug from: How to Build a REST API"]},
    {"id": 932, "tag": "data", "msgs": ["validate this URL: https://example.com/path?query=1"]},
    {"id": 933, "tag": "data", "msgs": ["generate a random 16-character password"]},
    {"id": 934, "tag": "data", "msgs": ["parse this cron expression: */5 * * * *"]},
    {"id": 935, "tag": "data", "msgs": ["convert this markdown to text: # Hello\\n## World\\n- item 1\\n- item 2"]},
    {"id": 936, "tag": "data", "msgs": ["what is my IP address"]},
    {"id": 937, "tag": "data", "msgs": ["generate a QR code for https://arqitect.ai"]},
    {"id": 938, "tag": "data", "msgs": ["detect the language of: Bonjour le monde"]},
    {"id": 939, "tag": "data", "msgs": ["fuzzy match 'tel avv' against ['Tel Aviv', 'Tehran', 'Tbilisi']"]},
    {"id": 940, "tag": "data", "msgs": ["analyze the sentiment of: I love this product, it's amazing!"]},
    {"id": 941, "tag": "data", "msgs": ["analyze the sentiment of: This is the worst experience ever"]},
    {"id": 942, "tag": "data", "msgs": ["format this number with commas: 1234567890"]},
    {"id": 943, "tag": "data", "msgs": ["extract all URLs from this text: Visit https://google.com or http://example.org for more"]},
    {"id": 944, "tag": "data", "msgs": ["convert this timestamp to a readable date: 1710432000"]},
    {"id": 945, "tag": "data", "msgs": ["generate a barcode for product code 1234567890"]},
    {"id": 946, "tag": "data", "msgs": ["validate this phone number: +972-50-123-4567"]},
    {"id": 947, "tag": "data", "msgs": ["what encoding is this file: UTF-8 or ASCII"]},
    {"id": 948, "tag": "data", "msgs": ["format this table: Name|Age|City\\nAlice|30|NYC\\nBob|25|LA"]},
    {"id": 949, "tag": "data", "msgs": ["convert 1024 bytes to human readable size"]},
    {"id": 950, "tag": "data", "msgs": ["generate a random hex color"]},
    {"id": 951, "tag": "data", "msgs": ["parse this regex and explain it: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"]},
    {"id": 952, "tag": "data", "msgs": ["create a regex to match URLs"]},
    {"id": 953, "tag": "data", "msgs": ["create a regex to match phone numbers"]},
    {"id": 954, "tag": "data", "msgs": ["convert this XML to JSON: <user><name>Alice</name><age>30</age></user>"]},
    {"id": 955, "tag": "data", "msgs": ["validate this credit card number: 4111111111111111"]},
    {"id": 956, "tag": "data", "msgs": ["extract emails from: Contact us at info@example.com or support@test.org"]},
    {"id": 957, "tag": "data", "msgs": ["generate lorem ipsum text (3 paragraphs)"]},
    {"id": 958, "tag": "data", "msgs": ["minify this JSON: { \"name\": \"test\", \"value\": 42 }"]},
    {"id": 959, "tag": "data", "msgs": ["diff these two strings: 'hello world' vs 'hello earth'"]},
    {"id": 960, "tag": "data", "msgs": ["count the words in: The quick brown fox jumps over the lazy dog"]},

    # ═══════════════════════════════════════════════════════════════════════
    # MULTILANG — Hebrew and multi-language (961-990)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 961, "tag": "multilang", "msgs": ["שלום"]},
    {"id": 962, "tag": "multilang", "msgs": ["מה שלומך"]},
    {"id": 963, "tag": "multilang", "msgs": ["ספר לי בדיחה"]},
    {"id": 964, "tag": "multilang", "msgs": ["מה מזג האוויר היום"]},
    {"id": 965, "tag": "multilang", "msgs": ["כמה זה 15 כפול 23"]},
    {"id": 966, "tag": "multilang", "msgs": ["תכתוב לי שיר קצר"]},
    {"id": 967, "tag": "multilang", "msgs": ["מי אתה"]},
    {"id": 968, "tag": "multilang", "msgs": ["תודה רבה"]},
    {"id": 969, "tag": "multilang", "msgs": ["מה השעה בניו יורק"]},
    {"id": 970, "tag": "multilang", "msgs": ["תרגם לאנגלית: שלום עולם"]},
    {"id": 971, "tag": "multilang", "msgs": ["bonjour, comment ça va?"]},
    {"id": 972, "tag": "multilang", "msgs": ["¿cómo está el clima hoy?"]},
    {"id": 973, "tag": "multilang", "msgs": ["translate 'good morning' to Japanese"]},
    {"id": 974, "tag": "multilang", "msgs": ["translate 'I love programming' to Spanish"]},
    {"id": 975, "tag": "multilang", "msgs": ["how do you say 'thank you' in 5 languages"]},
    {"id": 976, "tag": "multilang", "msgs": ["translate 'where is the train station' to French"]},
    {"id": 977, "tag": "multilang", "msgs": ["כתוב לי קוד פייתון שמחשב ממוצע של רשימת מספרים"]},
    {"id": 978, "tag": "multilang", "msgs": ["מה זה בינה מלאכותית"]},
    {"id": 979, "tag": "multilang", "msgs": ["תסביר לי מה זה API"]},
    {"id": 980, "tag": "multilang", "msgs": ["wie geht es Ihnen"]},
    {"id": 981, "tag": "multilang", "msgs": ["translate 'hello world' to Arabic"]},
    {"id": 982, "tag": "multilang", "msgs": ["ciao, come stai?"]},
    {"id": 983, "tag": "multilang", "msgs": ["привет мир"]},
    {"id": 984, "tag": "multilang", "msgs": ["こんにちは"]},
    {"id": 985, "tag": "multilang", "msgs": ["translate 'artificial intelligence' to Hebrew"]},
    {"id": 986, "tag": "multilang", "msgs": ["what does 'schadenfreude' mean"]},
    {"id": 987, "tag": "multilang", "msgs": ["translate 'the weather is nice today' to Italian"]},
    {"id": 988, "tag": "multilang", "msgs": ["מה ההבדל בין פייתון לג'אווהסקריפט"]},
    {"id": 989, "tag": "multilang", "msgs": ["תן לי חידה"]},
    {"id": 990, "tag": "multilang", "msgs": ["olá, tudo bem?"]},

    # ═══════════════════════════════════════════════════════════════════════
    # CONTEXT — multi-turn context-passing tests (991-1000)
    # ═══════════════════════════════════════════════════════════════════════
    {"id": 991, "tag": "context", "msgs": ["my name is Oron", "what's my name"]},
    {"id": 992, "tag": "context", "msgs": ["I live in Tel Aviv", "what's the weather where I live"]},
    {"id": 993, "tag": "context", "msgs": ["I'm working on a Python trading system", "what libraries should I use for backtesting"]},
    {"id": 994, "tag": "context", "msgs": ["calculate 25 * 4", "now add 50 to that result"]},
    {"id": 995, "tag": "context", "msgs": ["tell me about React hooks", "give me an example of useEffect"]},
    {"id": 996, "tag": "context", "msgs": ["what's the weather in London", "how about in Paris"]},
    {"id": 997, "tag": "context", "msgs": ["I need to plan a trip to Berlin", "what should I pack for the weather there"]},
    {"id": 998, "tag": "context", "msgs": ["write a Python function for fibonacci", "now add memoization to it"]},
    {"id": 999, "tag": "context", "msgs": ["who is Albert Einstein", "what was his most famous equation"]},
    {"id": 1000, "tag": "context", "msgs": ["I prefer TypeScript over JavaScript", "recommend a web framework for me"]},
]
